version: '3.7'

volumes:
  teste:

services:

  db:
    container_name: teste_database    
    restart: always
    build:
      context: .  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
